### ISSUE TITLE
Bug id

### ISSUE THREAD

**Issue by BesBettison** [trinhminhtriet/gitcoco#12]
### ISSUE TYPE:
 - Bug Report

#### OS / ENVIRONMENT:
1. [ ] Operating system: 
2. [ ] gitcoco version:

#### STEPS TO REPRODUCE:
1.
2.
3.

#### EXPECTED BEHAVIOUR:
explanation

#### ACTUAL BEHAVIOUR:
explanation

**Comment by trinhminhtriet** [comment]
Spam
